inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/*
    - frontend/**/*

Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update

Style/StringLiterals:
  EnforcedStyle: double_quotes
